# Generated by Django 2.2.4 on 2019-09-09 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortnerModule', '0003_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='user',
        ),
    ]
