# Generated by Django 2.2.4 on 2019-09-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortnerModule', '0004_remove_library_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='library/cover'),
        ),
    ]
